### ISSUE TITLE
Implement a test runner for syntax tests

### ISSUE THREAD

**Issue by snejugal** [fedor-ivn/project-f#8]
The test runner should test all files under `tests/syntax`. If the file ends with `.fail.lispf`, the test runner should try parsing every line from the file separately and ensure that the parser throws a syntax error. Otherwise, the test runner should ensure that the file successfully parses as a whole.

**Comment by fedor-ivn** [comment]
After all, shall we create a pipeline?)))

**Comment by snejugal** [comment]
@fedor-ivn you can do it if you want to
